services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
  spring:
    container_name: convo
    image: qudwns017/convo
    env_file:
      - .env
    ports:
      - 8081:8080
    depends_on:
      - redis
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${PSQL_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=convo
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27.4-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - convo
    restart: always
    networks:
      - external_network

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local