spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${PSQL_URL}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create