spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${PSQL_URL}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  jwt:
    secret: ${JWT_KEY}
    access-expired-time: ${JWT_ACCESS_EXPIRED_TIME}
    refresh-expired-time: ${JWT_REFRESH_EXPIRED_TIME}